networks:
  edu-platform-network:
    driver: bridge

services:
  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "16379:6379"          # expose to host if needed
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - edu-platform-network
    restart: no
  portal-db:
    image: postgres:16
    container_name: portal-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PORTAL_DB}
    ports:
      - "15432:5432"
    volumes:
      - pgdata-portal:/var/lib/postgresql/data
    networks:
      - edu-platform-network
    restart: unless-stopped
  lab-creator-db:
    image: postgres:16
    container_name: lab-creator-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_LABCREATOR_DB}
    ports:
      - "15433:5432"
    volumes:
      - pgdata-lab-creator:/var/lib/postgresql/data
    networks:
      - edu-platform-network
    restart: no
      
  portal-api:
    build: ./portal/server
    container_name: portal-api
    ports:
      - "15000:5000"
      - "5555:5555"
    environment:
      DATABASE_URL: ${PORTAL_DATABASE_URL}
      LAB_CREATOR_API_URL: ${LAB_CREATOR_API_URL}
      PORT: ${PORT}
      SESSION_SECRET: ${SESSION_SECRET}
      SERVER_URL: ${SERVER_URL}
      CLIENT_URL: ${CLIENT_URL}
      NODE_ENV: ${NODE_ENV}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RUN_ASSIGNMENT_WORKER: true
    depends_on:
      - portal-db
      - redis
    volumes:
      - ./portal/server:/app
     # - portal-api-node-modules:/app/node_modules
  #  command: nodemon app.js <<-- verride CMD in dockerfile
    networks:
      - edu-platform-network
    restart: no

  portal-client:
    build: ./portal/client
    container_name: portal-client
    ports:
      - "13000:3000"
    environment:
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      REACT_APP_API_LAB_HOST: ${REACT_APP_API_LAB_HOST}
      # Add WebSocket configuration to enable hotreloading
      WDS_SOCKET_PORT: 13000 #lets websocket  use main react port
      FAST_REFRESH: true
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - portal-api
    volumes:
      - ./portal/client:/app
    #  - portal-client-node-modules:/app/node_modules
    command: npm start
    networks:
      - edu-platform-network
    restart: no
    extra_hosts:
      - "host.docker.internal:host-gateway"

  lab-creator-api:
    build: ./lab-creator/server
    container_name: lab-creator-api
    ports:
      - "14000:4000"
      - "5556:5555"
    environment:
      DATABASE_URL: ${LABCREATOR_DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - lab-creator-db
    volumes:
      - ./lab-creator/server:/app
    #  - lab-creator-api-node-modules:/app/node_modules
   # command: npx nodemon app.js
    networks:
      - edu-platform-network
    restart: no
    extra_hosts:
      - "host.docker.internal:host-gateway"



volumes:
  pgdata-portal:
  pgdata-lab-creator:
